//go:build !ignore_autogenerated

package v1alpha1

// Copied from argo-rollouts' deepcopy-gen output, restricted to the Rollout closure.
// Upstream aliases meta/v1 as v1; it is spelled metav1 here to match the rest of the
// repository.

import (
	"encoding/json"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALBStatus) DeepCopyInto(out *ALBStatus) {
	*out = *in
	out.LoadBalancer = in.LoadBalancer
	out.CanaryTargetGroup = in.CanaryTargetGroup
	out.StableTargetGroup = in.StableTargetGroup
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALBStatus.
func (in *ALBStatus) DeepCopy() *ALBStatus {
	if in == nil {
		return nil
	}
	out := new(ALBStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALBTrafficRouting) DeepCopyInto(out *ALBTrafficRouting) {
	*out = *in
	if in.StickinessConfig != nil {
		in, out := &in.StickinessConfig, &out.StickinessConfig
		*out = new(StickinessConfig)
		**out = **in
	}
	if in.Ingresses != nil {
		in, out := &in.Ingresses, &out.Ingresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALBTrafficRouting.
func (in *ALBTrafficRouting) DeepCopy() *ALBTrafficRouting {
	if in == nil {
		return nil
	}
	out := new(ALBTrafficRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmbassadorTrafficRouting) DeepCopyInto(out *AmbassadorTrafficRouting) {
	*out = *in
	if in.Mappings != nil {
		in, out := &in.Mappings, &out.Mappings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmbassadorTrafficRouting.
func (in *AmbassadorTrafficRouting) DeepCopy() *AmbassadorTrafficRouting {
	if in == nil {
		return nil
	}
	out := new(AmbassadorTrafficRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisRunArgument) DeepCopyInto(out *AnalysisRunArgument) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(ArgumentValueFrom)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisRunArgument.
func (in *AnalysisRunArgument) DeepCopy() *AnalysisRunArgument {
	if in == nil {
		return nil
	}
	out := new(AnalysisRunArgument)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisRunMetadata) DeepCopyInto(out *AnalysisRunMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisRunMetadata.
func (in *AnalysisRunMetadata) DeepCopy() *AnalysisRunMetadata {
	if in == nil {
		return nil
	}
	out := new(AnalysisRunMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisRunStrategy) DeepCopyInto(out *AnalysisRunStrategy) {
	*out = *in
	if in.SuccessfulRunHistoryLimit != nil {
		in, out := &in.SuccessfulRunHistoryLimit, &out.SuccessfulRunHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.UnsuccessfulRunHistoryLimit != nil {
		in, out := &in.UnsuccessfulRunHistoryLimit, &out.UnsuccessfulRunHistoryLimit
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisRunStrategy.
func (in *AnalysisRunStrategy) DeepCopy() *AnalysisRunStrategy {
	if in == nil {
		return nil
	}
	out := new(AnalysisRunStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisTemplateRef) DeepCopyInto(out *AnalysisTemplateRef) {
	*out = *in
	if in.ClusterScope != nil {
		in, out := &in.ClusterScope, &out.ClusterScope
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisTemplateRef.
func (in *AnalysisTemplateRef) DeepCopy() *AnalysisTemplateRef {
	if in == nil {
		return nil
	}
	out := new(AnalysisTemplateRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntiAffinity) DeepCopyInto(out *AntiAffinity) {
	*out = *in
	if in.PreferredDuringSchedulingIgnoredDuringExecution != nil {
		in, out := &in.PreferredDuringSchedulingIgnoredDuringExecution, &out.PreferredDuringSchedulingIgnoredDuringExecution
		*out = new(PreferredDuringSchedulingIgnoredDuringExecution)
		**out = **in
	}
	if in.RequiredDuringSchedulingIgnoredDuringExecution != nil {
		in, out := &in.RequiredDuringSchedulingIgnoredDuringExecution, &out.RequiredDuringSchedulingIgnoredDuringExecution
		*out = new(RequiredDuringSchedulingIgnoredDuringExecution)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntiAffinity.
func (in *AntiAffinity) DeepCopy() *AntiAffinity {
	if in == nil {
		return nil
	}
	out := new(AntiAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApisixRoute) DeepCopyInto(out *ApisixRoute) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApisixRoute.
func (in *ApisixRoute) DeepCopy() *ApisixRoute {
	if in == nil {
		return nil
	}
	out := new(ApisixRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApisixTrafficRouting) DeepCopyInto(out *ApisixTrafficRouting) {
	*out = *in
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = new(ApisixRoute)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApisixTrafficRouting.
func (in *ApisixTrafficRouting) DeepCopy() *ApisixTrafficRouting {
	if in == nil {
		return nil
	}
	out := new(ApisixTrafficRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppMeshTrafficRouting) DeepCopyInto(out *AppMeshTrafficRouting) {
	*out = *in
	if in.VirtualService != nil {
		in, out := &in.VirtualService, &out.VirtualService
		*out = new(AppMeshVirtualService)
		(*in).DeepCopyInto(*out)
	}
	if in.VirtualNodeGroup != nil {
		in, out := &in.VirtualNodeGroup, &out.VirtualNodeGroup
		*out = new(AppMeshVirtualNodeGroup)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppMeshTrafficRouting.
func (in *AppMeshTrafficRouting) DeepCopy() *AppMeshTrafficRouting {
	if in == nil {
		return nil
	}
	out := new(AppMeshTrafficRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppMeshVirtualNodeGroup) DeepCopyInto(out *AppMeshVirtualNodeGroup) {
	*out = *in
	if in.CanaryVirtualNodeRef != nil {
		in, out := &in.CanaryVirtualNodeRef, &out.CanaryVirtualNodeRef
		*out = new(AppMeshVirtualNodeReference)
		**out = **in
	}
	if in.StableVirtualNodeRef != nil {
		in, out := &in.StableVirtualNodeRef, &out.StableVirtualNodeRef
		*out = new(AppMeshVirtualNodeReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppMeshVirtualNodeGroup.
func (in *AppMeshVirtualNodeGroup) DeepCopy() *AppMeshVirtualNodeGroup {
	if in == nil {
		return nil
	}
	out := new(AppMeshVirtualNodeGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppMeshVirtualNodeReference) DeepCopyInto(out *AppMeshVirtualNodeReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppMeshVirtualNodeReference.
func (in *AppMeshVirtualNodeReference) DeepCopy() *AppMeshVirtualNodeReference {
	if in == nil {
		return nil
	}
	out := new(AppMeshVirtualNodeReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppMeshVirtualService) DeepCopyInto(out *AppMeshVirtualService) {
	*out = *in
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppMeshVirtualService.
func (in *AppMeshVirtualService) DeepCopy() *AppMeshVirtualService {
	if in == nil {
		return nil
	}
	out := new(AppMeshVirtualService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgumentValueFrom) DeepCopyInto(out *ArgumentValueFrom) {
	*out = *in
	if in.PodTemplateHashValue != nil {
		in, out := &in.PodTemplateHashValue, &out.PodTemplateHashValue
		*out = new(ValueFromPodTemplateHash)
		**out = **in
	}
	if in.FieldRef != nil {
		in, out := &in.FieldRef, &out.FieldRef
		*out = new(FieldRef)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgumentValueFrom.
func (in *ArgumentValueFrom) DeepCopy() *ArgumentValueFrom {
	if in == nil {
		return nil
	}
	out := new(ArgumentValueFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsResourceRef) DeepCopyInto(out *AwsResourceRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsResourceRef.
func (in *AwsResourceRef) DeepCopy() *AwsResourceRef {
	if in == nil {
		return nil
	}
	out := new(AwsResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueGreenStatus) DeepCopyInto(out *BlueGreenStatus) {
	*out = *in
	if in.PrePromotionAnalysisRunStatus != nil {
		in, out := &in.PrePromotionAnalysisRunStatus, &out.PrePromotionAnalysisRunStatus
		*out = new(RolloutAnalysisRunStatus)
		**out = **in
	}
	if in.PostPromotionAnalysisRunStatus != nil {
		in, out := &in.PostPromotionAnalysisRunStatus, &out.PostPromotionAnalysisRunStatus
		*out = new(RolloutAnalysisRunStatus)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueGreenStatus.
func (in *BlueGreenStatus) DeepCopy() *BlueGreenStatus {
	if in == nil {
		return nil
	}
	out := new(BlueGreenStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueGreenStrategy) DeepCopyInto(out *BlueGreenStrategy) {
	*out = *in
	if in.PreviewReplicaCount != nil {
		in, out := &in.PreviewReplicaCount, &out.PreviewReplicaCount
		*out = new(int32)
		**out = **in
	}
	if in.AutoPromotionEnabled != nil {
		in, out := &in.AutoPromotionEnabled, &out.AutoPromotionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.ScaleDownDelaySeconds != nil {
		in, out := &in.ScaleDownDelaySeconds, &out.ScaleDownDelaySeconds
		*out = new(int32)
		**out = **in
	}
	if in.ScaleDownDelayRevisionLimit != nil {
		in, out := &in.ScaleDownDelayRevisionLimit, &out.ScaleDownDelayRevisionLimit
		*out = new(int32)
		**out = **in
	}
	if in.PrePromotionAnalysis != nil {
		in, out := &in.PrePromotionAnalysis, &out.PrePromotionAnalysis
		*out = new(RolloutAnalysis)
		(*in).DeepCopyInto(*out)
	}
	if in.AntiAffinity != nil {
		in, out := &in.AntiAffinity, &out.AntiAffinity
		*out = new(AntiAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.PostPromotionAnalysis != nil {
		in, out := &in.PostPromotionAnalysis, &out.PostPromotionAnalysis
		*out = new(RolloutAnalysis)
		(*in).DeepCopyInto(*out)
	}
	if in.PreviewMetadata != nil {
		in, out := &in.PreviewMetadata, &out.PreviewMetadata
		*out = new(PodTemplateMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.ActiveMetadata != nil {
		in, out := &in.ActiveMetadata, &out.ActiveMetadata
		*out = new(PodTemplateMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.AbortScaleDownDelaySeconds != nil {
		in, out := &in.AbortScaleDownDelaySeconds, &out.AbortScaleDownDelaySeconds
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueGreenStrategy.
func (in *BlueGreenStrategy) DeepCopy() *BlueGreenStrategy {
	if in == nil {
		return nil
	}
	out := new(BlueGreenStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryStatus) DeepCopyInto(out *CanaryStatus) {
	*out = *in
	if in.CurrentStepAnalysisRunStatus != nil {
		in, out := &in.CurrentStepAnalysisRunStatus, &out.CurrentStepAnalysisRunStatus
		*out = new(RolloutAnalysisRunStatus)
		**out = **in
	}
	if in.CurrentBackgroundAnalysisRunStatus != nil {
		in, out := &in.CurrentBackgroundAnalysisRunStatus, &out.CurrentBackgroundAnalysisRunStatus
		*out = new(RolloutAnalysisRunStatus)
		**out = **in
	}
	if in.Weights != nil {
		in, out := &in.Weights, &out.Weights
		*out = new(TrafficWeights)
		(*in).DeepCopyInto(*out)
	}
	if in.StepPluginStatuses != nil {
		in, out := &in.StepPluginStatuses, &out.StepPluginStatuses
		*out = make([]StepPluginStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryStatus.
func (in *CanaryStatus) DeepCopy() *CanaryStatus {
	if in == nil {
		return nil
	}
	out := new(CanaryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryStep) DeepCopyInto(out *CanaryStep) {
	*out = *in
	if in.SetWeight != nil {
		in, out := &in.SetWeight, &out.SetWeight
		*out = new(int32)
		**out = **in
	}
	if in.Pause != nil {
		in, out := &in.Pause, &out.Pause
		*out = new(RolloutPause)
		(*in).DeepCopyInto(*out)
	}
	if in.Experiment != nil {
		in, out := &in.Experiment, &out.Experiment
		*out = new(RolloutExperimentStep)
		(*in).DeepCopyInto(*out)
	}
	if in.Analysis != nil {
		in, out := &in.Analysis, &out.Analysis
		*out = new(RolloutAnalysis)
		(*in).DeepCopyInto(*out)
	}
	if in.SetCanaryScale != nil {
		in, out := &in.SetCanaryScale, &out.SetCanaryScale
		*out = new(SetCanaryScale)
		(*in).DeepCopyInto(*out)
	}
	if in.SetHeaderRoute != nil {
		in, out := &in.SetHeaderRoute, &out.SetHeaderRoute
		*out = new(SetHeaderRoute)
		(*in).DeepCopyInto(*out)
	}
	if in.SetMirrorRoute != nil {
		in, out := &in.SetMirrorRoute, &out.SetMirrorRoute
		*out = new(SetMirrorRoute)
		(*in).DeepCopyInto(*out)
	}
	if in.Plugin != nil {
		in, out := &in.Plugin, &out.Plugin
		*out = new(PluginStep)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryStep.
func (in *CanaryStep) DeepCopy() *CanaryStep {
	if in == nil {
		return nil
	}
	out := new(CanaryStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryStrategy) DeepCopyInto(out *CanaryStrategy) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]CanaryStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrafficRouting != nil {
		in, out := &in.TrafficRouting, &out.TrafficRouting
		*out = new(RolloutTrafficRouting)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxSurge != nil {
		in, out := &in.MaxSurge, &out.MaxSurge
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Analysis != nil {
		in, out := &in.Analysis, &out.Analysis
		*out = new(RolloutAnalysisBackground)
		(*in).DeepCopyInto(*out)
	}
	if in.AntiAffinity != nil {
		in, out := &in.AntiAffinity, &out.AntiAffinity
		*out = new(AntiAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.CanaryMetadata != nil {
		in, out := &in.CanaryMetadata, &out.CanaryMetadata
		*out = new(PodTemplateMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.StableMetadata != nil {
		in, out := &in.StableMetadata, &out.StableMetadata
		*out = new(PodTemplateMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleDownDelaySeconds != nil {
		in, out := &in.ScaleDownDelaySeconds, &out.ScaleDownDelaySeconds
		*out = new(int32)
		**out = **in
	}
	if in.ScaleDownDelayRevisionLimit != nil {
		in, out := &in.ScaleDownDelayRevisionLimit, &out.ScaleDownDelayRevisionLimit
		*out = new(int32)
		**out = **in
	}
	if in.AbortScaleDownDelaySeconds != nil {
		in, out := &in.AbortScaleDownDelaySeconds, &out.AbortScaleDownDelaySeconds
		*out = new(int32)
		**out = **in
	}
	if in.PingPong != nil {
		in, out := &in.PingPong, &out.PingPong
		*out = new(PingPongSpec)
		**out = **in
	}
	if in.MinPodsPerReplicaSet != nil {
		in, out := &in.MinPodsPerReplicaSet, &out.MinPodsPerReplicaSet
		*out = new(int32)
		**out = **in
	}
	if in.ReplicaProgressThreshold != nil {
		in, out := &in.ReplicaProgressThreshold, &out.ReplicaProgressThreshold
		*out = new(ReplicaProgressThreshold)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryStrategy.
func (in *CanaryStrategy) DeepCopy() *CanaryStrategy {
	if in == nil {
		return nil
	}
	out := new(CanaryStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DryRun) DeepCopyInto(out *DryRun) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DryRun.
func (in *DryRun) DeepCopy() *DryRun {
	if in == nil {
		return nil
	}
	out := new(DryRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldRef) DeepCopyInto(out *FieldRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldRef.
func (in *FieldRef) DeepCopy() *FieldRef {
	if in == nil {
		return nil
	}
	out := new(FieldRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderRoutingMatch) DeepCopyInto(out *HeaderRoutingMatch) {
	*out = *in
	if in.HeaderValue != nil {
		in, out := &in.HeaderValue, &out.HeaderValue
		*out = new(StringMatch)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderRoutingMatch.
func (in *HeaderRoutingMatch) DeepCopy() *HeaderRoutingMatch {
	if in == nil {
		return nil
	}
	out := new(HeaderRoutingMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioDestinationRule) DeepCopyInto(out *IstioDestinationRule) {
	*out = *in
	if in.AdditionalSubsetNames != nil {
		in, out := &in.AdditionalSubsetNames, &out.AdditionalSubsetNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioDestinationRule.
func (in *IstioDestinationRule) DeepCopy() *IstioDestinationRule {
	if in == nil {
		return nil
	}
	out := new(IstioDestinationRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioTrafficRouting) DeepCopyInto(out *IstioTrafficRouting) {
	*out = *in
	if in.VirtualService != nil {
		in, out := &in.VirtualService, &out.VirtualService
		*out = new(IstioVirtualService)
		(*in).DeepCopyInto(*out)
	}
	if in.DestinationRule != nil {
		in, out := &in.DestinationRule, &out.DestinationRule
		*out = new(IstioDestinationRule)
		(*in).DeepCopyInto(*out)
	}
	if in.VirtualServices != nil {
		in, out := &in.VirtualServices, &out.VirtualServices
		*out = make([]IstioVirtualService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioTrafficRouting.
func (in *IstioTrafficRouting) DeepCopy() *IstioTrafficRouting {
	if in == nil {
		return nil
	}
	out := new(IstioTrafficRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioVirtualService) DeepCopyInto(out *IstioVirtualService) {
	*out = *in
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLSRoutes != nil {
		in, out := &in.TLSRoutes, &out.TLSRoutes
		*out = make([]TLSRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TCPRoutes != nil {
		in, out := &in.TCPRoutes, &out.TCPRoutes
		*out = make([]TCPRoute, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioVirtualService.
func (in *IstioVirtualService) DeepCopy() *IstioVirtualService {
	if in == nil {
		return nil
	}
	out := new(IstioVirtualService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MangedRoutes) DeepCopyInto(out *MangedRoutes) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MangedRoutes.
func (in *MangedRoutes) DeepCopy() *MangedRoutes {
	if in == nil {
		return nil
	}
	out := new(MangedRoutes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeasurementRetention) DeepCopyInto(out *MeasurementRetention) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeasurementRetention.
func (in *MeasurementRetention) DeepCopy() *MeasurementRetention {
	if in == nil {
		return nil
	}
	out := new(MeasurementRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NginxTrafficRouting) DeepCopyInto(out *NginxTrafficRouting) {
	*out = *in
	if in.AdditionalIngressAnnotations != nil {
		in, out := &in.AdditionalIngressAnnotations, &out.AdditionalIngressAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.StableIngresses != nil {
		in, out := &in.StableIngresses, &out.StableIngresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CanaryIngressAnnotations != nil {
		in, out := &in.CanaryIngressAnnotations, &out.CanaryIngressAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NginxTrafficRouting.
func (in *NginxTrafficRouting) DeepCopy() *NginxTrafficRouting {
	if in == nil {
		return nil
	}
	out := new(NginxTrafficRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectRef.
func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil {
		return nil
	}
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PauseCondition) DeepCopyInto(out *PauseCondition) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PauseCondition.
func (in *PauseCondition) DeepCopy() *PauseCondition {
	if in == nil {
		return nil
	}
	out := new(PauseCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingPongSpec) DeepCopyInto(out *PingPongSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingPongSpec.
func (in *PingPongSpec) DeepCopy() *PingPongSpec {
	if in == nil {
		return nil
	}
	out := new(PingPongSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginStep) DeepCopyInto(out *PluginStep) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginStep.
func (in *PluginStep) DeepCopy() *PluginStep {
	if in == nil {
		return nil
	}
	out := new(PluginStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodTemplateMetadata) DeepCopyInto(out *PodTemplateMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodTemplateMetadata.
func (in *PodTemplateMetadata) DeepCopy() *PodTemplateMetadata {
	if in == nil {
		return nil
	}
	out := new(PodTemplateMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreferredDuringSchedulingIgnoredDuringExecution) DeepCopyInto(out *PreferredDuringSchedulingIgnoredDuringExecution) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreferredDuringSchedulingIgnoredDuringExecution.
func (in *PreferredDuringSchedulingIgnoredDuringExecution) DeepCopy() *PreferredDuringSchedulingIgnoredDuringExecution {
	if in == nil {
		return nil
	}
	out := new(PreferredDuringSchedulingIgnoredDuringExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaProgressThreshold) DeepCopyInto(out *ReplicaProgressThreshold) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaProgressThreshold.
func (in *ReplicaProgressThreshold) DeepCopy() *ReplicaProgressThreshold {
	if in == nil {
		return nil
	}
	out := new(ReplicaProgressThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequiredDuringSchedulingIgnoredDuringExecution) DeepCopyInto(out *RequiredDuringSchedulingIgnoredDuringExecution) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequiredDuringSchedulingIgnoredDuringExecution.
func (in *RequiredDuringSchedulingIgnoredDuringExecution) DeepCopy() *RequiredDuringSchedulingIgnoredDuringExecution {
	if in == nil {
		return nil
	}
	out := new(RequiredDuringSchedulingIgnoredDuringExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollbackWindowSpec) DeepCopyInto(out *RollbackWindowSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollbackWindowSpec.
func (in *RollbackWindowSpec) DeepCopy() *RollbackWindowSpec {
	if in == nil {
		return nil
	}
	out := new(RollbackWindowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rollout) DeepCopyInto(out *Rollout) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rollout.
func (in *Rollout) DeepCopy() *Rollout {
	if in == nil {
		return nil
	}
	out := new(Rollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Rollout) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutAnalysis) DeepCopyInto(out *RolloutAnalysis) {
	*out = *in
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = make([]AnalysisTemplateRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]AnalysisRunArgument, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = make([]DryRun, len(*in))
		copy(*out, *in)
	}
	if in.MeasurementRetention != nil {
		in, out := &in.MeasurementRetention, &out.MeasurementRetention
		*out = make([]MeasurementRetention, len(*in))
		copy(*out, *in)
	}
	if in.AnalysisRunMetadata != nil {
		in, out := &in.AnalysisRunMetadata, &out.AnalysisRunMetadata
		*out = new(AnalysisRunMetadata)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutAnalysis.
func (in *RolloutAnalysis) DeepCopy() *RolloutAnalysis {
	if in == nil {
		return nil
	}
	out := new(RolloutAnalysis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutAnalysisBackground) DeepCopyInto(out *RolloutAnalysisBackground) {
	*out = *in
	in.RolloutAnalysis.DeepCopyInto(&out.RolloutAnalysis)
	if in.StartingStep != nil {
		in, out := &in.StartingStep, &out.StartingStep
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutAnalysisBackground.
func (in *RolloutAnalysisBackground) DeepCopy() *RolloutAnalysisBackground {
	if in == nil {
		return nil
	}
	out := new(RolloutAnalysisBackground)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutAnalysisRunStatus) DeepCopyInto(out *RolloutAnalysisRunStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutAnalysisRunStatus.
func (in *RolloutAnalysisRunStatus) DeepCopy() *RolloutAnalysisRunStatus {
	if in == nil {
		return nil
	}
	out := new(RolloutAnalysisRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutCondition) DeepCopyInto(out *RolloutCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutCondition.
func (in *RolloutCondition) DeepCopy() *RolloutCondition {
	if in == nil {
		return nil
	}
	out := new(RolloutCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutExperimentStep) DeepCopyInto(out *RolloutExperimentStep) {
	*out = *in
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = make([]RolloutExperimentTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Analyses != nil {
		in, out := &in.Analyses, &out.Analyses
		*out = make([]RolloutExperimentStepAnalysisTemplateRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = make([]DryRun, len(*in))
		copy(*out, *in)
	}
	in.AnalysisRunMetadata.DeepCopyInto(&out.AnalysisRunMetadata)
	if in.ScaleDownDelaySeconds != nil {
		in, out := &in.ScaleDownDelaySeconds, &out.ScaleDownDelaySeconds
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutExperimentStep.
func (in *RolloutExperimentStep) DeepCopy() *RolloutExperimentStep {
	if in == nil {
		return nil
	}
	out := new(RolloutExperimentStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutExperimentStepAnalysisTemplateRef) DeepCopyInto(out *RolloutExperimentStepAnalysisTemplateRef) {
	*out = *in
	if in.ClusterScope != nil {
		in, out := &in.ClusterScope, &out.ClusterScope
		*out = new(bool)
		**out = **in
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]AnalysisRunArgument, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutExperimentStepAnalysisTemplateRef.
func (in *RolloutExperimentStepAnalysisTemplateRef) DeepCopy() *RolloutExperimentStepAnalysisTemplateRef {
	if in == nil {
		return nil
	}
	out := new(RolloutExperimentStepAnalysisTemplateRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutExperimentTemplate) DeepCopyInto(out *RolloutExperimentTemplate) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Metadata.DeepCopyInto(&out.Metadata)
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(int32)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(TemplateService)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutExperimentTemplate.
func (in *RolloutExperimentTemplate) DeepCopy() *RolloutExperimentTemplate {
	if in == nil {
		return nil
	}
	out := new(RolloutExperimentTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutList) DeepCopyInto(out *RolloutList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Rollout, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutList.
func (in *RolloutList) DeepCopy() *RolloutList {
	if in == nil {
		return nil
	}
	out := new(RolloutList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RolloutList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutPause) DeepCopyInto(out *RolloutPause) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(intstr.IntOrString)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutPause.
func (in *RolloutPause) DeepCopy() *RolloutPause {
	if in == nil {
		return nil
	}
	out := new(RolloutPause)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutSpec) DeepCopyInto(out *RolloutSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Template.DeepCopyInto(&out.Template)
	if in.WorkloadRef != nil {
		in, out := &in.WorkloadRef, &out.WorkloadRef
		*out = new(ObjectRef)
		**out = **in
	}
	if in.RollbackWindow != nil {
		in, out := &in.RollbackWindow, &out.RollbackWindow
		*out = new(RollbackWindowSpec)
		**out = **in
	}
	in.Strategy.DeepCopyInto(&out.Strategy)
	if in.RevisionHistoryLimit != nil {
		in, out := &in.RevisionHistoryLimit, &out.RevisionHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.ProgressDeadlineSeconds != nil {
		in, out := &in.ProgressDeadlineSeconds, &out.ProgressDeadlineSeconds
		*out = new(int32)
		**out = **in
	}
	if in.RestartAt != nil {
		in, out := &in.RestartAt, &out.RestartAt
		*out = (*in).DeepCopy()
	}
	if in.Analysis != nil {
		in, out := &in.Analysis, &out.Analysis
		*out = new(AnalysisRunStrategy)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutSpec.
func (in *RolloutSpec) DeepCopy() *RolloutSpec {
	if in == nil {
		return nil
	}
	out := new(RolloutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutStatus) DeepCopyInto(out *RolloutStatus) {
	*out = *in
	if in.PauseConditions != nil {
		in, out := &in.PauseConditions, &out.PauseConditions
		*out = make([]PauseCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AbortedAt != nil {
		in, out := &in.AbortedAt, &out.AbortedAt
		*out = (*in).DeepCopy()
	}
	if in.CurrentStepIndex != nil {
		in, out := &in.CurrentStepIndex, &out.CurrentStepIndex
		*out = new(int32)
		**out = **in
	}
	if in.CollisionCount != nil {
		in, out := &in.CollisionCount, &out.CollisionCount
		*out = new(int32)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]RolloutCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Canary.DeepCopyInto(&out.Canary)
	in.BlueGreen.DeepCopyInto(&out.BlueGreen)
	if in.RestartedAt != nil {
		in, out := &in.RestartedAt, &out.RestartedAt
		*out = (*in).DeepCopy()
	}
	if in.ALB != nil {
		in, out := &in.ALB, &out.ALB
		*out = new(ALBStatus)
		**out = **in
	}
	if in.ALBs != nil {
		in, out := &in.ALBs, &out.ALBs
		*out = make([]ALBStatus, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutStatus.
func (in *RolloutStatus) DeepCopy() *RolloutStatus {
	if in == nil {
		return nil
	}
	out := new(RolloutStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutStrategy) DeepCopyInto(out *RolloutStrategy) {
	*out = *in
	if in.BlueGreen != nil {
		in, out := &in.BlueGreen, &out.BlueGreen
		*out = new(BlueGreenStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.Canary != nil {
		in, out := &in.Canary, &out.Canary
		*out = new(CanaryStrategy)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutStrategy.
func (in *RolloutStrategy) DeepCopy() *RolloutStrategy {
	if in == nil {
		return nil
	}
	out := new(RolloutStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutTrafficRouting) DeepCopyInto(out *RolloutTrafficRouting) {
	*out = *in
	if in.Istio != nil {
		in, out := &in.Istio, &out.Istio
		*out = new(IstioTrafficRouting)
		(*in).DeepCopyInto(*out)
	}
	if in.Nginx != nil {
		in, out := &in.Nginx, &out.Nginx
		*out = new(NginxTrafficRouting)
		(*in).DeepCopyInto(*out)
	}
	if in.ALB != nil {
		in, out := &in.ALB, &out.ALB
		*out = new(ALBTrafficRouting)
		(*in).DeepCopyInto(*out)
	}
	if in.SMI != nil {
		in, out := &in.SMI, &out.SMI
		*out = new(SMITrafficRouting)
		**out = **in
	}
	if in.Ambassador != nil {
		in, out := &in.Ambassador, &out.Ambassador
		*out = new(AmbassadorTrafficRouting)
		(*in).DeepCopyInto(*out)
	}
	if in.AppMesh != nil {
		in, out := &in.AppMesh, &out.AppMesh
		*out = new(AppMeshTrafficRouting)
		(*in).DeepCopyInto(*out)
	}
	if in.Traefik != nil {
		in, out := &in.Traefik, &out.Traefik
		*out = new(TraefikTrafficRouting)
		**out = **in
	}
	if in.ManagedRoutes != nil {
		in, out := &in.ManagedRoutes, &out.ManagedRoutes
		*out = make([]MangedRoutes, len(*in))
		copy(*out, *in)
	}
	if in.Apisix != nil {
		in, out := &in.Apisix, &out.Apisix
		*out = new(ApisixTrafficRouting)
		(*in).DeepCopyInto(*out)
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make(map[string]json.RawMessage, len(*in))
		for key, val := range *in {
			var outVal []byte
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(json.RawMessage, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.MaxTrafficWeight != nil {
		in, out := &in.MaxTrafficWeight, &out.MaxTrafficWeight
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutTrafficRouting.
func (in *RolloutTrafficRouting) DeepCopy() *RolloutTrafficRouting {
	if in == nil {
		return nil
	}
	out := new(RolloutTrafficRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteMatch) DeepCopyInto(out *RouteMatch) {
	*out = *in
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(StringMatch)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(StringMatch)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]StringMatch, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteMatch.
func (in *RouteMatch) DeepCopy() *RouteMatch {
	if in == nil {
		return nil
	}
	out := new(RouteMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMITrafficRouting) DeepCopyInto(out *SMITrafficRouting) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMITrafficRouting.
func (in *SMITrafficRouting) DeepCopy() *SMITrafficRouting {
	if in == nil {
		return nil
	}
	out := new(SMITrafficRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetCanaryScale) DeepCopyInto(out *SetCanaryScale) {
	*out = *in
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(int32)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetCanaryScale.
func (in *SetCanaryScale) DeepCopy() *SetCanaryScale {
	if in == nil {
		return nil
	}
	out := new(SetCanaryScale)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetHeaderRoute) DeepCopyInto(out *SetHeaderRoute) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = make([]HeaderRoutingMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetHeaderRoute.
func (in *SetHeaderRoute) DeepCopy() *SetHeaderRoute {
	if in == nil {
		return nil
	}
	out := new(SetHeaderRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetMirrorRoute) DeepCopyInto(out *SetMirrorRoute) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = make([]RouteMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Percentage != nil {
		in, out := &in.Percentage, &out.Percentage
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetMirrorRoute.
func (in *SetMirrorRoute) DeepCopy() *SetMirrorRoute {
	if in == nil {
		return nil
	}
	out := new(SetMirrorRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepPluginStatus) DeepCopyInto(out *StepPluginStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepPluginStatus.
func (in *StepPluginStatus) DeepCopy() *StepPluginStatus {
	if in == nil {
		return nil
	}
	out := new(StepPluginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StickinessConfig) DeepCopyInto(out *StickinessConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StickinessConfig.
func (in *StickinessConfig) DeepCopy() *StickinessConfig {
	if in == nil {
		return nil
	}
	out := new(StickinessConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringMatch) DeepCopyInto(out *StringMatch) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringMatch.
func (in *StringMatch) DeepCopy() *StringMatch {
	if in == nil {
		return nil
	}
	out := new(StringMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPRoute) DeepCopyInto(out *TCPRoute) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPRoute.
func (in *TCPRoute) DeepCopy() *TCPRoute {
	if in == nil {
		return nil
	}
	out := new(TCPRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSRoute) DeepCopyInto(out *TLSRoute) {
	*out = *in
	if in.SNIHosts != nil {
		in, out := &in.SNIHosts, &out.SNIHosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSRoute.
func (in *TLSRoute) DeepCopy() *TLSRoute {
	if in == nil {
		return nil
	}
	out := new(TLSRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateService) DeepCopyInto(out *TemplateService) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateService.
func (in *TemplateService) DeepCopy() *TemplateService {
	if in == nil {
		return nil
	}
	out := new(TemplateService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraefikTrafficRouting) DeepCopyInto(out *TraefikTrafficRouting) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraefikTrafficRouting.
func (in *TraefikTrafficRouting) DeepCopy() *TraefikTrafficRouting {
	if in == nil {
		return nil
	}
	out := new(TraefikTrafficRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficWeights) DeepCopyInto(out *TrafficWeights) {
	*out = *in
	out.Canary = in.Canary
	out.Stable = in.Stable
	if in.Additional != nil {
		in, out := &in.Additional, &out.Additional
		*out = make([]WeightDestination, len(*in))
		copy(*out, *in)
	}
	if in.Verified != nil {
		in, out := &in.Verified, &out.Verified
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficWeights.
func (in *TrafficWeights) DeepCopy() *TrafficWeights {
	if in == nil {
		return nil
	}
	out := new(TrafficWeights)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightDestination) DeepCopyInto(out *WeightDestination) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightDestination.
func (in *WeightDestination) DeepCopy() *WeightDestination {
	if in == nil {
		return nil
	}
	out := new(WeightDestination)
	in.DeepCopyInto(out)
	return out
}
