//go:build !ignore_autogenerated

package v1alpha1

// Copied from Kong's deepcopy-gen output, restricted to the KongRoute and KongService
// closures.

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ControlPlaneRef) DeepCopyInto(out *ControlPlaneRef) {
	*out = *in
	if in.KonnectID != nil {
		in, out := &in.KonnectID, &out.KonnectID
		*out = new(KonnectIDType)
		**out = **in
	}
	if in.KonnectNamespacedRef != nil {
		in, out := &in.KonnectNamespacedRef, &out.KonnectNamespacedRef
		*out = new(KonnectNamespacedRef)
		**out = **in
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ControlPlaneRef.
func (in *ControlPlaneRef) DeepCopy() *ControlPlaneRef {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneRef)
	in.DeepCopyInto(out)
	return out
}

func (in *Destinations) DeepCopyInto(out *Destinations) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new Destinations.
func (in *Destinations) DeepCopy() *Destinations {
	if in == nil {
		return nil
	}
	out := new(Destinations)
	in.DeepCopyInto(out)
	return out
}

func (in *KongRoute) DeepCopyInto(out *KongRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new KongRoute.
func (in *KongRoute) DeepCopy() *KongRoute {
	if in == nil {
		return nil
	}
	out := new(KongRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KongRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KongRouteAPISpec) DeepCopyInto(out *KongRouteAPISpec) {
	*out = *in
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]Destinations, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HTTPSRedirectStatusCode != nil {
		in, out := &in.HTTPSRedirectStatusCode, &out.HTTPSRedirectStatusCode
		*out = new(HTTPSRedirectStatusCode)
		**out = **in
	}
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PathHandling != nil {
		in, out := &in.PathHandling, &out.PathHandling
		*out = new(PathHandling)
		**out = **in
	}
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreserveHost != nil {
		in, out := &in.PreserveHost, &out.PreserveHost
		*out = new(bool)
		**out = **in
	}
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = make([]RouteJSONProtocols, len(*in))
		copy(*out, *in)
	}
	if in.RegexPriority != nil {
		in, out := &in.RegexPriority, &out.RegexPriority
		*out = new(int64)
		**out = **in
	}
	if in.RequestBuffering != nil {
		in, out := &in.RequestBuffering, &out.RequestBuffering
		*out = new(bool)
		**out = **in
	}
	if in.ResponseBuffering != nil {
		in, out := &in.ResponseBuffering, &out.ResponseBuffering
		*out = new(bool)
		**out = **in
	}
	if in.Snis != nil {
		in, out := &in.Snis, &out.Snis
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]Sources, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StripPath != nil {
		in, out := &in.StripPath, &out.StripPath
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(Tags, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new KongRouteAPISpec.
func (in *KongRouteAPISpec) DeepCopy() *KongRouteAPISpec {
	if in == nil {
		return nil
	}
	out := new(KongRouteAPISpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KongRouteList) DeepCopyInto(out *KongRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KongRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new KongRouteList.
func (in *KongRouteList) DeepCopy() *KongRouteList {
	if in == nil {
		return nil
	}
	out := new(KongRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KongRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KongRouteSpec) DeepCopyInto(out *KongRouteSpec) {
	*out = *in
	if in.ControlPlaneRef != nil {
		in, out := &in.ControlPlaneRef, &out.ControlPlaneRef
		*out = new(ControlPlaneRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceRef != nil {
		in, out := &in.ServiceRef, &out.ServiceRef
		*out = new(ServiceRef)
		(*in).DeepCopyInto(*out)
	}
	in.KongRouteAPISpec.DeepCopyInto(&out.KongRouteAPISpec)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new KongRouteSpec.
func (in *KongRouteSpec) DeepCopy() *KongRouteSpec {
	if in == nil {
		return nil
	}
	out := new(KongRouteSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KongRouteStatus) DeepCopyInto(out *KongRouteStatus) {
	*out = *in
	if in.Konnect != nil {
		in, out := &in.Konnect, &out.Konnect
		*out = new(KonnectEntityStatusWithControlPlaneAndServiceRefs)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new KongRouteStatus.
func (in *KongRouteStatus) DeepCopy() *KongRouteStatus {
	if in == nil {
		return nil
	}
	out := new(KongRouteStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *KongService) DeepCopyInto(out *KongService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new KongService.
func (in *KongService) DeepCopy() *KongService {
	if in == nil {
		return nil
	}
	out := new(KongService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KongService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KongServiceAPISpec) DeepCopyInto(out *KongServiceAPISpec) {
	*out = *in
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(int64)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.ReadTimeout != nil {
		in, out := &in.ReadTimeout, &out.ReadTimeout
		*out = new(int64)
		**out = **in
	}
	if in.Retries != nil {
		in, out := &in.Retries, &out.Retries
		*out = new(int64)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(Tags, len(*in))
		copy(*out, *in)
	}
	if in.TLSVerify != nil {
		in, out := &in.TLSVerify, &out.TLSVerify
		*out = new(bool)
		**out = **in
	}
	if in.TLSVerifyDepth != nil {
		in, out := &in.TLSVerifyDepth, &out.TLSVerifyDepth
		*out = new(int64)
		**out = **in
	}
	if in.WriteTimeout != nil {
		in, out := &in.WriteTimeout, &out.WriteTimeout
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new KongServiceAPISpec.
func (in *KongServiceAPISpec) DeepCopy() *KongServiceAPISpec {
	if in == nil {
		return nil
	}
	out := new(KongServiceAPISpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KongServiceList) DeepCopyInto(out *KongServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KongService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new KongServiceList.
func (in *KongServiceList) DeepCopy() *KongServiceList {
	if in == nil {
		return nil
	}
	out := new(KongServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KongServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KongServiceSpec) DeepCopyInto(out *KongServiceSpec) {
	*out = *in
	if in.ControlPlaneRef != nil {
		in, out := &in.ControlPlaneRef, &out.ControlPlaneRef
		*out = new(ControlPlaneRef)
		(*in).DeepCopyInto(*out)
	}
	in.KongServiceAPISpec.DeepCopyInto(&out.KongServiceAPISpec)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new KongServiceSpec.
func (in *KongServiceSpec) DeepCopy() *KongServiceSpec {
	if in == nil {
		return nil
	}
	out := new(KongServiceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KongServiceStatus) DeepCopyInto(out *KongServiceStatus) {
	*out = *in
	if in.Konnect != nil {
		in, out := &in.Konnect, &out.Konnect
		*out = new(KonnectEntityStatusWithControlPlaneRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new KongServiceStatus.
func (in *KongServiceStatus) DeepCopy() *KongServiceStatus {
	if in == nil {
		return nil
	}
	out := new(KongServiceStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *KonnectEntityStatus) DeepCopyInto(out *KonnectEntityStatus) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new KonnectEntityStatus.
func (in *KonnectEntityStatus) DeepCopy() *KonnectEntityStatus {
	if in == nil {
		return nil
	}
	out := new(KonnectEntityStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *KonnectEntityStatusWithControlPlaneAndServiceRefs) DeepCopyInto(out *KonnectEntityStatusWithControlPlaneAndServiceRefs) {
	*out = *in
	out.KonnectEntityStatus = in.KonnectEntityStatus
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new KonnectEntityStatusWithControlPlaneAndServiceRefs.
func (in *KonnectEntityStatusWithControlPlaneAndServiceRefs) DeepCopy() *KonnectEntityStatusWithControlPlaneAndServiceRefs {
	if in == nil {
		return nil
	}
	out := new(KonnectEntityStatusWithControlPlaneAndServiceRefs)
	in.DeepCopyInto(out)
	return out
}

func (in *KonnectEntityStatusWithControlPlaneRef) DeepCopyInto(out *KonnectEntityStatusWithControlPlaneRef) {
	*out = *in
	out.KonnectEntityStatus = in.KonnectEntityStatus
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new KonnectEntityStatusWithControlPlaneRef.
func (in *KonnectEntityStatusWithControlPlaneRef) DeepCopy() *KonnectEntityStatusWithControlPlaneRef {
	if in == nil {
		return nil
	}
	out := new(KonnectEntityStatusWithControlPlaneRef)
	in.DeepCopyInto(out)
	return out
}

func (in *KonnectNamespacedRef) DeepCopyInto(out *KonnectNamespacedRef) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new KonnectNamespacedRef.
func (in *KonnectNamespacedRef) DeepCopy() *KonnectNamespacedRef {
	if in == nil {
		return nil
	}
	out := new(KonnectNamespacedRef)
	in.DeepCopyInto(out)
	return out
}

func (in *NameRef) DeepCopyInto(out *NameRef) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new NameRef.
func (in *NameRef) DeepCopy() *NameRef {
	if in == nil {
		return nil
	}
	out := new(NameRef)
	in.DeepCopyInto(out)
	return out
}

func (in *ServiceRef) DeepCopyInto(out *ServiceRef) {
	*out = *in
	if in.NamespacedRef != nil {
		in, out := &in.NamespacedRef, &out.NamespacedRef
		*out = new(NameRef)
		**out = **in
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ServiceRef.
func (in *ServiceRef) DeepCopy() *ServiceRef {
	if in == nil {
		return nil
	}
	out := new(ServiceRef)
	in.DeepCopyInto(out)
	return out
}

func (in *Sources) DeepCopyInto(out *Sources) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new Sources.
func (in *Sources) DeepCopy() *Sources {
	if in == nil {
		return nil
	}
	out := new(Sources)
	in.DeepCopyInto(out)
	return out
}

func (in Tags) DeepCopyInto(out *Tags) {
	{
		in := &in
		*out = make(Tags, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new Tags.
func (in Tags) DeepCopy() Tags {
	if in == nil {
		return nil
	}
	out := new(Tags)
	in.DeepCopyInto(out)
	return *out
}
